---
oauth:
    consumer:
        key: 'ck'
        secret: 'cs'
    access_token:
        key: 'atk'
        secret: 'ats'

items:
    - name: 'ドクターペッパー 500mlペット*24本'
      url: 'http://www.amazon.co.jp/dp/B001U7651A/'
    - name: 'ドクターペッパー 350ml缶*24本'
      url: 'http://www.amazon.co.jp/dp/B001DDOIBU/'
...
